version: '3'

services:
  mysql-training-dev:
    image: mysql:latest
    container_name: mysql-training-container-dev
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: dev_training_db
    ports:
      - "3307:3306"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411