#spring:
#  application:
#    name: training-microservice
#  config:
#    import: configserver:http://localhost:8888
#    name: training-microservice
#    activate:
#      on-profile: default, dev


server:
  port: ${PORT:${SERVER_PORT:8083}}
spring:
  application:
    name: training-microservice
  profiles:
    active: dev
  #  mvc:
  #    pathmatch:
  #      matching-strategy: ANT_PATH_MATCHER

  cloud:
    config:
      enabled: false
    compatibility-verifier:
      enabled: false
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
#      base-path: "/manage"

springdoc:
  api-docs:
    enabled: 'true'
    path: /api-docs
  swagger-ui:
    enabled: 'true'
    path: /swagger-ui-custom.html

  show-actuator: true

