spring:
  application:
    name: training-microservice
  config:
    import: configserver:http://localhost:8888
    name: training-microservice
    activate:
      on-profile: default, dev
#  cloud:
#    config:
#
#      uri: http://localhost:8888
#      name: training-microservice

springdoc: # OpenAPI (Swagger) Configuration
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html