server:
  port: ${PORT:${SERVER_PORT:8083}}
spring:
  application:
    name: training-microservice
  profiles:
    active: prod, mongo, integration
  cloud:
    loadbalancer:
      enabled: false
    config:
      enabled: false
    compatibility-verifier:
      enabled: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    hostname: localhost


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS

springdoc:
  api-docs:
    enabled: 'true'
  swagger-ui:
    enabled: 'true'
    path: /doc/swagger-ui.html

  show-actuator: true


